apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-react-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-react-chat
  template:
    metadata:
      labels:
        app: go-react-chat
    spec:
      containers:
        - name: api
          image: ivenyao/go-react-chat-api:v1
          ports:
            - containerPort: 8080

        - name: frontend
          image: ivenyao/go-react-chat-frontend:v1
          ports:
            - containerPort: 9000

        - name: db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
